package mywechat.store.auto;

import org.apache.cayenne.CayenneDataObject;

import mywechat.store.Users;

/**
 * Class _Friends was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Friends extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String TO_FRIEND_PROPERTY = "toFriend";
    public static final String TO_MY_SELF_PROPERTY = "toMySelf";

    public static final String ID_PK_COLUMN = "id";

    public void setId(int id) {
        writeProperty(ID_PROPERTY, id);
    }
    public int getId() {
        Object value = readProperty(ID_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setToFriend(Users toFriend) {
        setToOneTarget(TO_FRIEND_PROPERTY, toFriend, true);
    }

    public Users getToFriend() {
        return (Users)readProperty(TO_FRIEND_PROPERTY);
    }


    public void setToMySelf(Users toMySelf) {
        setToOneTarget(TO_MY_SELF_PROPERTY, toMySelf, true);
    }

    public Users getToMySelf() {
        return (Users)readProperty(TO_MY_SELF_PROPERTY);
    }


}
