package mywechat.store.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import mywechat.store.Users;

/**
 * Class _Messages was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Messages extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String MSG_CONTENT_PROPERTY = "msgContent";
    public static final String MSG_TYPE_PROPERTY = "msgType";
    public static final String SEND_TIME_PROPERTY = "sendTime";
    public static final String TO_RECEIVER_PROPERTY = "toReceiver";
    public static final String TO_SENDER_PROPERTY = "toSender";

    public static final String ID_PK_COLUMN = "id";

    public void setId(int id) {
        writeProperty(ID_PROPERTY, id);
    }
    public int getId() {
        Object value = readProperty(ID_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setMsgContent(String msgContent) {
        writeProperty(MSG_CONTENT_PROPERTY, msgContent);
    }
    public String getMsgContent() {
        return (String)readProperty(MSG_CONTENT_PROPERTY);
    }

    public void setMsgType(String msgType) {
        writeProperty(MSG_TYPE_PROPERTY, msgType);
    }
    public String getMsgType() {
        return (String)readProperty(MSG_TYPE_PROPERTY);
    }

    public void setSendTime(Date sendTime) {
        writeProperty(SEND_TIME_PROPERTY, sendTime);
    }
    public Date getSendTime() {
        return (Date)readProperty(SEND_TIME_PROPERTY);
    }

    public void setToReceiver(Users toReceiver) {
        setToOneTarget(TO_RECEIVER_PROPERTY, toReceiver, true);
    }

    public Users getToReceiver() {
        return (Users)readProperty(TO_RECEIVER_PROPERTY);
    }


    public void setToSender(Users toSender) {
        setToOneTarget(TO_SENDER_PROPERTY, toSender, true);
    }

    public Users getToSender() {
        return (Users)readProperty(TO_SENDER_PROPERTY);
    }


}
