package mywechat.store.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import mywechat.store.Friends;
import mywechat.store.Messages;

/**
 * Class _Users was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Users extends CayenneDataObject {

    public static final String CELL_PHONE_PROPERTY = "cellPhone";
    public static final String ID_PROPERTY = "id";
    public static final String NICK_NAME_PROPERTY = "nickName";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String PORTRAIT_PROPERTY = "portrait";
    public static final String AS_FRIENDS_ARRAY_PROPERTY = "asFriendsArray";
    public static final String MESSAGES_ARRAY_PROPERTY = "messagesArray";
    public static final String MESSAGES_ARRAY1_PROPERTY = "messagesArray1";
    public static final String MY_FRIENDS_ARRAY_PROPERTY = "myFriendsArray";

    public static final String ID_PK_COLUMN = "id";

    public void setCellPhone(String cellPhone) {
        writeProperty(CELL_PHONE_PROPERTY, cellPhone);
    }
    public String getCellPhone() {
        return (String)readProperty(CELL_PHONE_PROPERTY);
    }

    public void setId(int id) {
        writeProperty(ID_PROPERTY, id);
    }
    public int getId() {
        Object value = readProperty(ID_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setNickName(String nickName) {
        writeProperty(NICK_NAME_PROPERTY, nickName);
    }
    public String getNickName() {
        return (String)readProperty(NICK_NAME_PROPERTY);
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword() {
        return (String)readProperty(PASSWORD_PROPERTY);
    }

    public void setPortrait(String portrait) {
        writeProperty(PORTRAIT_PROPERTY, portrait);
    }
    public String getPortrait() {
        return (String)readProperty(PORTRAIT_PROPERTY);
    }

    public void addToAsFriendsArray(Friends obj) {
        addToManyTarget(AS_FRIENDS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromAsFriendsArray(Friends obj) {
        removeToManyTarget(AS_FRIENDS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Friends> getAsFriendsArray() {
        return (List<Friends>)readProperty(AS_FRIENDS_ARRAY_PROPERTY);
    }


    public void addToMessagesArray(Messages obj) {
        addToManyTarget(MESSAGES_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMessagesArray(Messages obj) {
        removeToManyTarget(MESSAGES_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Messages> getMessagesArray() {
        return (List<Messages>)readProperty(MESSAGES_ARRAY_PROPERTY);
    }


    public void addToMessagesArray1(Messages obj) {
        addToManyTarget(MESSAGES_ARRAY1_PROPERTY, obj, true);
    }
    public void removeFromMessagesArray1(Messages obj) {
        removeToManyTarget(MESSAGES_ARRAY1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Messages> getMessagesArray1() {
        return (List<Messages>)readProperty(MESSAGES_ARRAY1_PROPERTY);
    }


    public void addToMyFriendsArray(Friends obj) {
        addToManyTarget(MY_FRIENDS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMyFriendsArray(Friends obj) {
        removeToManyTarget(MY_FRIENDS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Friends> getMyFriendsArray() {
        return (List<Friends>)readProperty(MY_FRIENDS_ARRAY_PROPERTY);
    }


}
